### PR TITLE
Add server requirements

### LINKED ISSUE #60: Adding requirements
For the new version we should add something like "You should use privacyIDEA 3.0 or higher" in [README.md](https://github.com/privacyidea/privacyidea-owncloud-app/blob/master/README.md) and [info.xml](https://github.com/privacyidea/privacyidea-owncloud-app/blob/master/twofactor_privacyidea/appinfo/info.xml). Else the push token and triggerchallenge may not work correctly.

### PR DESCRIPTION
**Pull request by Mipronimo**
Adding requirements for the server.
This is necessary, if you want to use PUSH or TiQR token.
closes #60

### CODE REVIEW

**Review by tamaro-skaljic — APPROVED** [review]
Good!
Is it possible to check the current server version in our owncloud plugin so that our customers can ensure that they use the right version?

**Comment by Mipronimo** [comment]
> Good!
> Is it possible to check the current server version in our owncloud plugin so that our customers can ensure that they use the right version?

We cannot do this, before the app is installed, cause you need the connection to the privacyIDEA server, but I implemented a check now in https://github.com/privacyidea/privacyidea-owncloud-app/pull/67/commits/8dab7f4b0450c148f4fe5b4ed4d24c7aeb5d59b8

**Comment by Mipronimo** [comment]
We could add an array for recommended versions, if more than one version are recommended

**Comment by Mipronimo** [comment]
> We could add an array for recommended versions, if more than one version are recommended

Fixed in eb11381

**Comment by tamaro-skaljic** [comment]
Nice. :)

**Pull request merged**
