### PR TITLE
Check service account rights

### LINKED ISSUE #21: Check service account rights
#17 checks whether the service account credentials are correct by fetching an auth token. In addition, we could check if the logged-in user has the ``triggerchallenge`` right.

### PR DESCRIPTION
**Pull request by Mipronimo**
Added triggerChallenge with entered service account and the user "triggerChallengeTest"
If the response is not 403, the service account is allowed to do triggerChallgenes.
closes #21

### CODE REVIEW

**Comment by cornelinux** [comment]
The more elegant way would be to investigate the response from the ``/auth`` request and look into result->value->rights. In this list should be "triggerchallenge".

**Comment by cornelinux** [comment]
@fredreichbier Is this the right place? Wouldn't it test on every auth request? I think it would be sufficient to test the rights only on the TEST button.

**Comment by fredreichbier** [comment]
Hm, I agree it would be nicer to test the rights only when the "test" button is clicked. Otherwise, we would end up with one extra HTTP request per authentication, and this can get slow :)

**Review by fredreichbier — APPROVED** [review]
Looks nice to me!

**Pull request merged**
